# Generated by Django 4.1.7 on 2023-03-19 21:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields
import multiselectfield.validators


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='amenities',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Laundry'), (2, 'Parking'), (3, 'Room Service'), (4, 'Swimming Pool'), (5, 'Gym'), (6, 'Breakfast included'), (7, 'Late Checkout')], default=[], max_length=13, validators=[multiselectfield.validators.MaxValueMultiFieldValidator(8)]),
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('message', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('pend', 'pend'), ('deni', 'deni'), ('expi', 'expi'), ('appr', 'appr'), ('canc', 'canc'), ('term', 'term'), ('comp', 'comp')], default='pend', max_length=4)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='properties.property')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_is_host', models.BooleanField()),
                ('is_read', models.BooleanField(default=False)),
                ('notification_type', models.IntegerField()),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profilenotis', to=settings.AUTH_USER_MODEL)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.reservation')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_type', models.BooleanField()),
                ('is_root_comment', models.BooleanField()),
                ('comment_text', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('parent_comment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='properties.comments')),
                ('related_reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.reservation')),
            ],
        ),
    ]
