# Generated by Django 4.1.7 on 2023-03-19 22:44

from django.db import migrations
import multiselectfield.db.fields
import multiselectfield.validators


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_property_amenities_reservation_notifications_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='amenities',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Laundry'), (2, 'Parking'), (3, 'Room Service'), (4, 'Swimming Pool'), (5, 'Gym'), (6, 'Breakfast included'), (7, 'Late Checkout')], default=[], max_length=13, validators=[multiselectfield.validators.MaxValueMultiFieldValidator(7)]),
        ),
    ]
