# Generated by Django 4.1.7 on 2023-04-01 02:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('properties', '0005_amenities_remove_property_amenities_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='related_reservation',
        ),
        migrations.AddField(
            model_name='comments',
            name='child_comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child', to='properties.comments'),
        ),
        migrations.AddField(
            model_name='comments',
            name='related_property',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='properties.property'),
        ),
        migrations.AddField(
            model_name='comments',
            name='related_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notifications',
            name='notification',
            field=models.CharField(default=None, max_length=600),
        ),
        migrations.AlterField(
            model_name='comments',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comments',
            name='parent_comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent', to='properties.comments'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('pend', 'pend'), ('deni', 'deni'), ('expi', 'expi'), ('appr', 'appr'), ('canc', 'canc'), ('term', 'term'), ('comp', 'comp'), ('peca', 'peca')], default='pend', max_length=4),
        ),
    ]
